#!/usr/bin/env bash
# Bash script that displays information for the specified subdomain
func_print () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    func_print "$2.$1" "$2"
else
    func_print "www.$1" "www"
    func_print "lb-01.$1" "lb-01"
    func_print "web-01.$1" "web-01"
    func_print "web-02.$1" "web-02"
fi
