#!/bin/env bash

# Check if the correct number of parameters were passed
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Get the parameters
file_path=$1
ip_address=$2
username=$3
ssh_key_path=$4

# Disable strict host key checking
scp -o StrictHostKeyChecking=no $username@$ip_address

# Transfer the file
scp -i $ssh_key_path $file_path $username@$ip_address:~/
