#!/usr/bin/env bash
# Check if the correct number of parameters were passed
if [ $# -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  # Get the parameters
  file_path=$1
  ip_address=$2
  username=$3
  ssh_key_path=$4 
  # Disable strict host key checking # Transfer the file
  scp -o "StrictHostKeyChecking=no" -i "$ssh_key_path" "$file_path" "$username@$ip_address:~/"
fi
