#!/usr/bin/env bash
#install Nginx on web-01
#NGINX should be listening on port 80
#when querying NGINX at its root ? with a GET request must show the string Hello World
#without using systemctl for restarting nginx

sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World!"
sudo ufw restart nginx 80
