#!/usr/bin/env bash
#install Nginx on web-01
#NGINX should be listening on port 80
#when querying NGINX at its root ? with a GET request must show the string Hello World
#without using systemctl for restarting nginx

sudo apt-get -y update
sudo apt-get install -y nginx
sudo mkdir -p /var/www/html
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
