#!/usr/bin/env bash
# Install Nginx on web-01
# NGINX should be listening on port 80
# When querying NGINX at its root "/" with a GET request must show the string "Hello World"
# Without using systemctl for restarting nginx

DEST="/etc/nginx/sites-available/default"
ADD="/listen 80 default_server;/rewrite ^redirect_me https://youtube.com;"
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 80
sudo mkdir -p /var/www/html
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start

# Use sed to insert the new location block into the default nginx configuration file
sed -i "$ADD" "$DEST"

# Restart nginx without using systemctl
sudo service nginx restart
