#!/usr/bin/env bash
# Install Nginx on web-01
# NGINX should be listening on port 80
# When querying NGINX at its root "/" with a GET request must show the string "Hello World"
# Without using systemctl for restarting nginx

sudo chmod 777 /etc/nginx/sites-available/

WHERE="/etc/nginx/sites-available/default"
ADD="\\\tlocation \/redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
E404="\\\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"


apt-get -y update
apt-get install -y nginx

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sed -i "30i $ADD" $WHERE
echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/custom_404.html
sed -i "48i $E404" $WHERE


# Restart Nginx
service nginx restart

