#!/usr/bin/env bash
# Install Nginx on web-01
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

sudo chmod 777 /etc/nginx/sites-available/

WHERE="/etc/nginx/sites-available/default"
ADD="\\\tlocation \/redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

apt-get -y update
apt-get install -y nginx

echo "Hello WOrld!" | sudo tee /usr/share/nginx/html/index.html
sed -i "30i $ADD" $WHERE
echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/custom_404.html
sed -i "48i $E404" $WHERE

#Restart Nginx
service nginx restart
