#!/bin/bash
#configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02), the name of the custom HTTP Header must be X-served-By
sudo apt-get update
sudo apt-get install nginx
s
