#!/usr/bin/env bash
#Bash script that configures HAproxy so that it send traffic to web-01 and web-02,distributes requests using a roundrobin algorithm and the HAproxy server can be managed via an init script

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 187642-web-01 54.90.59.65:80 check
    server 187642-web-02 18.235.248.54:80 check
"
# Update packages
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart

