#!/usr/bin/env bash
#Bash script that configures HAproxy so that it send traffic to web-01 and web-02,distributes requests using a roundrobin algorithm and the HAproxy server can be managed via an init script

sudo apt-get update
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get update && apt-get upgrade -y
sudo apt-get install -y haproxy=2.8.\*
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.copy
echo -e "\nfrontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend http_back\n\tbalance roundrobin\n\tserver 187642-web-01 54.90.59.65:80 check\n\tserver 187642-web-02 18.235.248.54:80 check" >> /etc/haproxy/haproxy.cfg
sudo service rsylog restart
sudo service haproxy restart