#!/usr/bin/env bash
# debugging Nginx web server and configures a server to listening on port 80 of all the servers's active IPV4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/
service nginx restart
pkill -f "nginx"
