#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

name="To infinity and beyond"
num=1
echo $$ >> /var/run/myscript.pid

while [ "$num" -eq 1 ]; do
	trap "echo I hate the kill command" SIGTERM
	trap "Y U no love me?!" SIGINT
	trap "$rm /var/run/myscript.pid && exit 0" SIGQUIT | SIGTERM
	echo "$name"
	sleep 2
done
