#!/usr/bin/env bash
# Script that displays To infinity and beyond indefinitely

name="To infinity and beyond"
num=1
while [ "$num" -eq 1 ]; do
	trap "echo I am invincible!!!" SIGTERM
	echo "$name"
	sleep 2
done
