#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd

num=1
while [ "$num" -lt 101 ]; do
    if (( num%3 == 0 && num%5 == 0)); then
        echo "FizzBuzz"
    elif ((num%5==0)); then
        echo "Buzz"
    elif ((num%3 == 0)); then
        echo "Fizz"
    else
        echo "$num"
    fi
    ((num++))
done