#!/usr/bin/env bash
# This script is displays numbers from 1 to 20

msg="bad luck from China"
msg1="bad luck from Japan"
msg2="bad luck from Italy"
num=1
while [ "$num" -lt 21 ]; do
	echo "$num"
	# case statement
	case $num in 
		4)
			echo "$msg"
	case $num in 
		9)
			echo "$msg1"
	case $num in 
		17)
			echo "$msg2"
	((num++))
done
