#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes:
# displays hours from 0 to 12 
# displays minutes from 1 to 59

hour=0
while [ "$hour" -lt 13 ]; do
	echo "Hour: $hour"
	minutes=1
	while [ "$minutes" -lt 60 ]; do
		echo "$minutes"
		((minutes++))
	done
	((hour++))
done
