#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirement
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
sudo chown root:root /etc/hosts
sudo chmod 644 /etc/hosts

