#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirement
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8
echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
# Restart the networking service
sudo service networking restart
