#!/usr/bin/env bash
#script that displays all active IPv4 IPs on the machine it’s executed on.
interfaces=$(ip -o addr show scope global | awk '/inet/ {print $2}')

# Loop through the list of interfaces and print the IP addresses
for interface in $interfaces; do
	ip_address=$(ip -o addr show "$interface" | awk '/inet/ {print $4}')
    echo "$ip_address"
done
