#!/bin/bash
#Bash script that uses ssh to connect to server using a private key ~/.ssh/school with the user ubuntu
# using only one ssh single-character flags
#with out using -l

ssh -i ~/.ssh/id ubuntu@187642-web-01187642-web-01187642-web-01