#!/usr/bin/env bash
# SSH Client configuration configured using the private key ~/.ssh/school
# SSH Client configuration configured to refuse to authenticate a password

Host my-server
    Hostname 187642-web-01
    IdentifyFile ~/.ssh/school
    PassWordAuthenticationls
    