#!/usr/bin/env bash
# SSH Client configuration configured using the private key ~/.ssh/school
# SSH Client configuration configured to refuse to authenticate a password

Host 187642-web-01
    Hostname ubuntu
    IdentifyFile ~/.ssh/school
    PassWordAuthentication no
    
